config/routes.rb
Rails.application.routes.draw do
  root  'welcome#index' 
  
  resources :users, only: [:new, :create, :show] do 
    resources :cryptocurrencies
  end 
  namespace :admin do 
    resources :categories
    resources :images
  end 
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true 
  has_many :cryptocurrencies
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
  validates :name, presence: true 
  validates :amount, numericality: { greater_than: 0 }
  belongs_to :user 
  belongs_to :category
  has_many :cryptocurrency_images
  has_many :images, through: :cryptocurrency_images

end

app/models/cryptocurrency_image.rb
class CryptocurrencyImage < ApplicationRecord 
  belongs_to :image
  belongs_to :cryptocurrency
end

app/models/image.rb
class Image < ApplicationRecord 
  has_many :cryptocurrency_images 
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, uniqueness: true  
  has_secure_password
  has_many :cryptocurrencies

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController 
 
  def index 
    @categories = Category.all
  end 

  def new 
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save 
      flash[:success] = "Successfully created your category"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to admin_categories_path
  end

  private 
  
  def category_params
    params.require(:category).permit(:title, :description)
  end
end 

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def index
    @images = Image.all
  end 

  def new 
    @image = Image.new
  end

  def create
    @image = Image.create(image_params)
    if @image.save 
      flash[:success] = "Successfully created your image"
      redirect_to admin_images_path
    else
      render :new
    end 
  end 
  
  private 
  def image_params
    params.require(:image).permit(:url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def current_admin?
    current_user && current_user.admin?
  end
  
end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController 
  before_action :require_owner, only: [:new, :create, :destroy, :edit, :update]

  def current_owner?
    params[:user_id].to_i == current_user.id
  end

  def require_owner
    render file: "public/404" unless current_owner?
  end

  def index 
    @cryptocurrencies = Cryptocurrency.where(user_id: params[:user_id]) 
    @btc = Cryptocompare::Price.find('BTC', 'USD')["BTC"]["USD"]
  end

  def new 
    @cryptocurrency = Cryptocurrency.new 
  end 

  def create
    @cryptocurrency = Cryptocurrency.new(cryptocurrency_params)
    @cryptocurrency.user_id = params[:user_id]

    if @cryptocurrency.save 
       flash[:success] = "Successfully created your cryptocurrency"
       redirect_to  user_cryptocurrencies_path(params[:user_id])
    else
      render :new 
    end 
   
  end 

  def destroy 
    @cryptocurrency = Cryptocurrency.find(params[:id])
    if @cryptocurrency.destroy
      flash[:success] = "Successfully deleted your cryptocurrency"
      redirect_to user_cryptocurrencies_path(params[:user_id])
    else
      render :index
    end 
  end 

  def edit 
    @user = User.find(params[:user_id])
    @cryptocurrency = Cryptocurrency.find(params[:id])
  end 

  def update 
    @cryptocurrency = Cryptocurrency.find(params[:id])
    @cryptocurrency.update(cryptocurrency_params)
    if @cryptocurrency.save
      flash[:success]= "Successfully updated your cryptocurrency"
      redirect_to user_cryptocurrencies_path(params[:user_id])
    else
      @user = User.find(params[:user_id])
      render :edit
    end 
  end

  

  private 
  
  def cryptocurrency_params 
    params.require(:cryptocurrency).permit(:name, :amount, :symbol, :category_id, image_ids: [])
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def new 
    
  end

  def create
    user = User.find_by(user_name: user_params[:user_name])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.user_name}"
      redirect_to user_cryptocurrencies_path(user)
    else
      render :new
    end
  end 

  private
    def user_params 
      params.require(:user).permit(:user_name, :password)
    end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
    @user = User.new
  end 
  
  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = "Welcome #{@user.user_name}"
      session[:user_id] = @user.id
      redirect_to  user_cryptocurrencies_path(@user)
    else
      flash[:alert] = "User already exists"
      render :new 
    end
    
    
  end

  def show 
    @user = User.find(params[:id])
  end 

  private
    def user_params
      params.require(:user).permit(:user_name, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Categories</li>
            </ol>
          </nav>

        </div>
    </div>
</div>









<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <h1>Categories</h1>
          <%= link_to "Create new category", new_admin_category_path, :class => "btn btn-sm btn-pill btn-success  ",  style: 'float:right;'  %>
          <p>Explore existing categories or create a new one with your admin rights</p>
        </div>
    </div>
</div>



<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <p></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <p></p>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
        <% @categories.each do |category|%>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= category.title %></h3>
          </div>
          <div class="panel-body">
            <%= category.description %> <%= link_to "Delete", admin_category_path(category), style: 'float:right;', :class => "btn btn-xs btn-pill btn-danger", method: :delete %> 
          </div>
        </div>
        <% end %>
        
        </div>
    </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item"><a href="/admin/categories">Categories</a></li>
              <li class="breadcrumb-item active" aria-current="page">New</li>
            </ol>
          </nav>

        </div>
    </div>
</div>













<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <h1>New category</h1>
          <p>Enter the details for your new category in the form below</p>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-xs-12">
          
          <%= form_for [:admin, @category] do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title, :class => "form-control" %>

            <%= f.label :description %>
            <%= f.text_field :description, :class => "form-control" %>

            <%= f.submit "Create category", :class => 'btn btn-sm btn-pill btn-success',style: 'float:right; margin-top: 40px;'%>
          <% end %>
        
        
        </div>
    </div>
</div>

app/views/admin/images/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Images</li>
            </ol>
          </nav>

        </div>
    </div>
</div>









<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <h1>Images</h1>
          <%= link_to "Create new image", new_admin_image_path, :class => "btn btn-sm btn-pill btn-success  ",  style: 'float:right;'  %>
          <p>Explore existing images or create a new one with your admin rights</p>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <p></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <p></p>
        </div>
    </div>
</div>



<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
          <div class="row">

            <% @images.each do |image| %>
            <div class="col-xs-6 col-md-3">
              <a href="#" class="thumbnail">
                <img data-src="holder.js/100%x180" alt="100%x180" src="<%= image.url %>" data-holder-rendered="true" style="height: 180px; width: 100%; display: block;">
              </a>
            </div>
            <% end %>

          </div>

    
        </div>
    </div>
</div>

app/views/admin/images/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item"><a href="/admin/images">Images</a></li>
              <li class="breadcrumb-item active" aria-current="page">New</li>
            </ol>
          </nav>

        </div>
    </div>
</div>













<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <h1>New image</h1>
          <p>Enter the url for your new image in the form below</p>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-xs-12">

          <%= form_for [:admin, @image] do |f| %>
            <%= f.label :url %>
            <%= f.text_field :url, :class => "form-control"%>

            <%= f.submit "Create image", :class => 'btn btn-sm btn-pill btn-success',style: 'float:right; margin-top: 40px;' %>
          <% end %>

        </div>
    </div>
</div>

app/views/cryptocurrencies/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item"><a href="/users/<%= @user.id %>/cryptocurrencies"><%= current_user.user_name %> Portfolio</a></li>
              <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
          </nav>

        </div>
    </div>
</div>






<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <h1>Edit <%= @cryptocurrency.name %> </h1>
          <p>Alter the attributes of this coin below and save your changes</p>
        </div>
    </div>
     <div class="row">
        <div class="col-md-3">

          <%= form_for [@user, @cryptocurrency] do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, :class => "form-control" %>

            <%= f.label :amount %>
            <%= f.number_field :amount, :class => "form-control" %>
            
            <%= f.label :symbol %>
            <%= f.text_field :symbol, :class => "form-control" %>

            <%= f.label :category %>
            <%= f.collection_select :category_id, Category.all, :id, :title, {prompt: "Select a category"}, {class: "form-control"}  %>

            <%= f.label :cryptocurrency_images %>
            <%= f.select :image_ids, Image.all.collect {|x| [x.url, x.id]}, {}, :multiple => true %>


           

            <%= f.submit 'Update cryptocurrency',:class => 'btn btn-sm btn-pill btn-success',style: 'float:right; margin-top: 40px;'  %>
           
          <% end %>
        

        </div>
    </div>
</div>

app/views/cryptocurrencies/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page"><%= current_user.user_name %> Portfolio</li>
            </ol>
          </nav>

        </div>
    </div>
</div>





<div class="container">
    <div class="row">
        <div class="col-xs-12">
         <%= link_to "Log out",  root_path, :class => "btn btn-sm btn-pill btn-default  ",  style: 'float:right;' %>
          <p>1BTC = $<%= @btc %></p>
          <h1>Your portfolio</h1>
          <p>Explore your current market allocations below</p>
          <%= link_to "Add cryptocurrency",  new_user_cryptocurrency_path(params[:user_id]), :class => "btn btn-sm btn-pill btn-success  ",  style: 'float:right;' %>
          <% if current_user.admin? %>
            <%= link_to "Add category",  admin_categories_path, :class => "btn btn-sm btn-pill btn-primary",  style: 'float:right; margin-right: 10px;' %>
            <%= link_to "Add image",  admin_images_path, :class => "btn btn-sm btn-pill btn-info  ",  style: 'float:right; margin-right: 10px;' %>
          <% end %>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <p></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <p></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">

          <div class="row">

            <% @cryptocurrencies.each do |cryptocurrency| %>
            <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                <img data-src="holder.js/100%x200" alt="100%x200" src= <%= cryptocurrency.images[0].url %> data-holder-rendered="true" style="height: 200px; width: 100%; display: block;">
                <div class="caption">
                  <h3 id="thumbnail-label"><%= cryptocurrency.name %><small> (<%= cryptocurrency.symbol %>)</small></h3>
                  <p>Tokens held: <%= cryptocurrency.amount %></p>
                  <p><%= link_to "Edit", edit_user_cryptocurrency_path(params[:user_id], cryptocurrency), :class => "btn btn-xs btn-pill btn-warning"  %> <%= link_to "Delete", user_cryptocurrency_path(params[:user_id], cryptocurrency), :class => "btn btn-xs btn-pill btn-danger", method: :delete %></p>
                </div>
              </div>
            </div>
            <% end %>
           

          </div>


        
        </div>
    </div>
</div>

app/views/cryptocurrencies/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <h1>New cryptocurrency</h1>
          <p>Enter the details for your new asset in the form below</p>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-xs-12">
        
        <%= form_for [current_user, @cryptocurrency] do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name, :class => "form-control" %>

          <%= f.label :amount %>
          <%= f.number_field :amount, :class => "form-control" %>
          
          <%= f.label :symbol %>
          <%= f.text_field :symbol, :class => "form-control"   %>

          <%= f.label :category %>
          <%= f.collection_select :category_id, Category.all, :id, :title, {prompt: "Select a category"}, {class: "form-control"}   %>


          <%= f.label :cryptocurrency_images %>

          <div class="container">
            <div class="row">
                <%= f.select :image_ids, Image.all.collect {|x| [x.url, x.id]}, {}, :multiple => true %>
            </div>
          </div>

          <%= f.submit "Create cryptocurrency", :class => 'btn btn-sm btn-pill btn-success',style: 'float:right; margin-top: 40px;' %>
        <% end %>
        
        
        
        
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  
    <div class="container">
    <div class="row">
        <div class="col-xs-12">
           <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, class: "alert alert-success" %>
            <% end %>
        </div>
    </div>
</div>
   

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
          <h1>Sign up</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
        
                  
          <%= form_for(@user) do |f| %>
            <%= f.label :user_name %>
            <%= f.text_field :user_name, :class => "form-control" %>

            <%= f.label :password %>
            <%= f.password_field :password, :class => "form-control"%>

            <%= f.submit 'Create Account ', :class => 'btn btn-sm btn-pill btn-success',style: 'float:right; margin-top: 40px;' %>
            
          <% end %>

        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= @user.user_name %>

app/views/welcome/index.html.erb
<link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed p-x-0" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../">
        <span>Crypto Box</span>
      </a>
    </div>
    <div class="navbar-collapse collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Sign up", new_user_path %>
        </li>
        <li>
          <%= link_to "Login", login_path %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>


 
<div class="container text-center">
  <h1 class="block-title m-b-sm text-uppercase app-myphone-brand">Crypto Box</h1>
  <p class="lead m-b-lg p-b-md">Cryptocurrency portfolio management for all</p>
</div>









  <div class="container">
    <div class="row">
    </div>
    <div class="row">
      <div class="col-sm-6">
        <ul class="featured-list">
          <li class="m-b-lg">
            <div class="featured-list-icon text-primary">
              <i class="fa fa-picture-o" aria-hidden="true"></i>
            </div>
            <p class="featured-list-icon-text m-b-0"><strong>Upload unlimited images</strong></p>
            <p class="featured-list-icon-text">
              Store the latest news releases and infographs related to your cryptocurrencies, take full advantage of our blazing fast speeds.
            </p>
          </li>

          <li class="m-b-lg">
            <div class="featured-list-icon text-primary">
              <i class="fa fa-tag" aria-hidden="true"></i>
            </div>
            <p class="featured-list-icon-text m-b-0"><strong>Assign categories</strong></p>
            <p class="featured-list-icon-text">
              Divide your portfolio into meaningful sections carefully created by our admin users.
            </p>
          </li>

        </ul>
      </div>
      <div class="col-sm-6">
        <ul class="featured-list">

          <li class="m-b-lg">
            <div class="featured-list-icon text-primary">
              <i class="fa fa-lock" aria-hidden="true"></i>
            </div>
            <p class="featured-list-icon-text m-b-0"><strong>Secure from anywhere</strong></p>
            <p class="featured-list-icon-text">
              Our hashing algorithm and state of the art security ensures no matter what, only you will be able to alter your portfolio allocation.
            </p>
          </li>

          <li class="m-b-lg">
            <div class="featured-list-icon text-primary">
              <i class="fa fa-bar-chart" aria-hidden="true"></i>
            </div>
            <p class="featured-list-icon-text m-b-0"><strong>Real time price data</strong></p>
            <p class="featured-list-icon-text">
              Watch your portfolio grow in real time, we will never limit the number of cryptocurrencies you can hold.
            </p>
          </li>
        </ul>
      </div>
    </div>
  </div>







<div class="block block-bordered-lg text-center">
  <div class="container text-center app-translate-15" data-transition="entrance" style="transition: transform 1200ms cubic-bezier(0.2, 0.7, 0.5, 1); transform: none;">
      <blockquote class="pull-quote">
        <img class="img-circle" src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/4/005/077/305/329f88b.jpg">
        <p>
          “Allocations. Diversification. Market news. They all have one thing in common…literally no one enjoys managing them. Cryptobox, brings all that complexity into one easy to use tool.”
        </p>
        <cite>Nico Lewis, Creator of Crypto Box</cite>
      </blockquote>
    </div>
  </div>
</div>

<div class="block block-bordered-lg text-center">
  <div class="container-fluid">
    <p class="lead m-b-md">
      Join over <strong> 90,000 </strong> crypto enthusiasts already using Crypto Box.
    </p>
    <small class="text-muted">
      By creating an account I agree to Crypto Box's
      <a href="#">Terms of service</a>
    </small>
  </div>
</div>
  
  